services:
   palworld:
      build: .
      restart: unless-stopped
      container_name: palkemon
      stop_grace_period: 30s
      ports:
        - 50223:8211/udp
        - 50224:27015/udp
      environment:
        PLAYERS: 2
        MULTITHREADING: true
        COMMUNITY: false
        SERVER_NAME: palkemon
        SERVER_PASSWORD: ${PALWORLD_SERVER_PASSWORD}
      volumes:
         - ${PALWORLD_SERVER_DIR}:/palworld
